name: painter2_example
description: Demonstrates how to use the painter2 plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.4.0

  cupertino_icons: ^0.1.2
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  painter2:
    path: ../

flutter:

  uses-material-design: true
